learning_rate: 0.0005
batch_size: 64
sigma: 500
experience_replay: 24
n_train_gp_best: 2200
n_train_gp_rand: 1350
max_bo_iter: 10000
bo_batch_size: 1180
fp_radius: 2
fp_nbits: 4096
initial_population_size: 340
max_inner_loop_iter: 50
population_size: 120
offspring_size: 70
mutation_rate: .067
max_generations: 2
max_ga_start_population_size: 1000
ga_pool_num_carryover: 250
ga_pool_num_best: 250
